name: Build for Windows

on:
  workflow_dispatch:    # запуск вручную
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure up-to-date Rust
        run: |
          rustup update
          rustup default stable

      - name: Build release
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pipisenok-game-windows
          path: target/release/pipisenok-game.exe
