name: Build Pipisenok Game

# Запускать workflow вручную (workflow_dispatch) или при коммитах в ветку main
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      # Получаем код
      - uses: actions/checkout@v4

      # Установка системных зависимостей Bevy
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libudev-dev pkg-config

      # Настройка стабильного Rust‑toolchain
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          override: true

      # Кэш Cargo для ускорения повторных сборок
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Сборка релизной версии
      - name: Build release
        run: cargo build --release --locked

      # Загрузка бинарника и папки assets как артефакта
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pipisenok-game-linux
          path: |
            target/release/pipisenok-game
            assets
